name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check documentation files
      run: |
        echo "Checking documentation files..."
        if [ -f "README.md" ]; then
          echo "✅ README.md exists"
        else
          echo "❌ README.md missing"
        fi
        
        if [ -d "docs" ]; then
          echo "✅ docs/ directory exists"
          echo "Documentation files:"
          find docs/ -name "*.md" | head -10
        else
          echo "❌ docs/ directory missing"
        fi
        
        echo "Documentation check completed"